-- Project-scoped synthetic data. Content is stored privately by the server generator.
create table public.synthetic_profiles (
  id uuid primary key default gen_random_uuid(), workspace_id uuid, project_id uuid not null references public.projects(id) on delete cascade,
  test_data_id text not null, display_name text not null, first_name text not null, last_name text not null, email_1 text not null,
  email_2 text not null default '', mobile text not null default '', telephone text not null default '', street text not null default '', postcode text not null default '', city text not null default '', country text not null default 'DE', nationality text not null default 'DE', date_of_birth date, availability_date date, linkedin_url text not null default '', focus_area text not null default '', employment_type text not null default '', skills_json jsonb not null default '[]', roles_json jsonb not null default '[]', work_history_json jsonb not null default '[]', education_history_json jsonb not null default '[]', language text not null default 'de', synthetic boolean not null default true check (synthetic), version integer not null default 1 check (version > 0), created_at timestamptz not null default timezone('utc', now()), created_by uuid not null references auth.users(id), updated_at timestamptz not null default timezone('utc', now()), unique(project_id, test_data_id, version)
);
create table public.test_data_artifacts (
  id uuid primary key default gen_random_uuid(), workspace_id uuid, project_id uuid not null references public.projects(id) on delete cascade, case_id text not null, profile_id uuid not null references public.synthetic_profiles(id) on delete cascade, test_data_id text not null, artifact_type text not null, document_role text not null default 'CV', file_name text not null, mime_type text not null, language text not null default 'de', version integer not null default 1, storage_path text, checksum text, expected_main_cv boolean not null default false, negative_variant text, generation_status text not null default 'draft', created_at timestamptz not null default timezone('utc', now()), created_by uuid not null references auth.users(id)
);
create table public.test_data_expectations (
  id uuid primary key default gen_random_uuid(), artifact_id uuid not null references public.test_data_artifacts(id) on delete cascade, field_domain text not null, display_name text not null, technical_name text, expected_value jsonb, comparison_rule text not null, required boolean not null default false, intentionally_missing boolean not null default false, intentionally_invalid boolean not null default false, notes text
);
create table public.test_case_artifact_links (case_id text not null, artifact_id uuid not null references public.test_data_artifacts(id) on delete cascade, usage_type text not null default 'primary', active boolean not null default true, created_at timestamptz not null default timezone('utc', now()), primary key(case_id, artifact_id));
alter table public.synthetic_profiles enable row level security; alter table public.test_data_artifacts enable row level security; alter table public.test_data_expectations enable row level security; alter table public.test_case_artifact_links enable row level security;
create policy "Members read synthetic profiles" on public.synthetic_profiles for select to authenticated using (public.is_project_member(project_id));
create policy "Testers create synthetic profiles" on public.synthetic_profiles for insert to authenticated with check (synthetic and public.has_project_role(project_id, array['Project Owner','Test Designer','Tester']));
create policy "Admins manage synthetic profiles" on public.synthetic_profiles for all to authenticated using (public.has_project_role(project_id, array['Project Owner','Test Designer']));
create policy "Members read test data artifacts" on public.test_data_artifacts for select to authenticated using (public.is_project_member(project_id));
create policy "Testers create test data artifacts" on public.test_data_artifacts for insert to authenticated with check (public.has_project_role(project_id, array['Project Owner','Test Designer','Tester']));
create policy "Members read expectations" on public.test_data_expectations for select to authenticated using (exists (select 1 from public.test_data_artifacts a where a.id = artifact_id and public.is_project_member(a.project_id)));
create policy "Members read artifact links" on public.test_case_artifact_links for select to authenticated using (exists (select 1 from public.test_data_artifacts a where a.id = artifact_id and public.is_project_member(a.project_id)));